### ISSUE TITLE
Publish source file to pypi

### ISSUE THREAD

**Issue by wchresta** [jspahrsummers/adt#23]
Looking at the [published files in pypi](https://pypi.org/project/algebraic-data-types/#files) we can see that there is no source file published. Compare that with, for example [the attr package on pypi](https://pypi.org/project/attr/#files).

Having the ability to download the source from pypi is useful for down-stream systems that consume dependencies from pypi but want to build packages themselves.

**Comment by jspahrsummers** [comment]
This certainly isn't a deliberate omission. It must be a bug in [the `deploy` script](https://github.com/jspahrsummers/adt/blob/daaa38f29812c5b262fefc30e019d45b2bb5bbe9/script/deploy), if you'd be interested in submitting a pull request.

The source releases are tagged on the GitHub repository, in the meantime: https://github.com/jspahrsummers/adt/releases
